export const RESUME_STORE_DATA = "RESUME_STORE_DATA";
export const RESUME_CLEAR_DATA = "RESUME_CLEAR_DATA";
export const RESUME_STORE_TEMPLATE = "RESUME_STORE_TEMPLATE";
export const RESUME_STORE_COLOR = "RESUME_STORE_COLOR";
